name: gym_app
description: A GYM management application for gym owner.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.4.0
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  get:
  intl:
  flutter_slidable:
  page_transition:
  animated_splash_screen:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/gym.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
